name: bicycling_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  go_router: ^13.2.1
  shared_preferences: ^2.2.1
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  package_info_plus: ^5.0.1
  meta:
  intl: ^0.18.0
  dropdown_button2: ^2.3.9
  flutter_screenutil: ^5.9.0
  dartz: ^0.10.1
  flutter_local_notifications: ^17.0.0
  flutter_svg: ^2.0.7
  keyboard_dismisser: ^3.0.0
  phone_form_field: ^8.1.0
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.21
  textfield_datepicker: ^0.2.0
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.5.3
  syncfusion_flutter_datepicker: ^25.1.35
  expandable: ^5.0.1
  chewie: ^1.7.1
  url_launcher: ^6.2.1
  youtube_player_flutter: ^9.0.0-beta.0
  video_url_validator: ^1.0.3
  galleryimage: ^2.0.1
  responsive_grid: ^2.4.4
  image_picker: ^1.0.4
  duration: ^3.0.13
  webview_flutter: ^4.4.2
  textfield_state: ^0.3.0
  signature: ^5.4.1
  dotted_border: ^2.1.0
  path_provider: ^2.1.1
  smooth_page_indicator: ^1.1.0

  requests_inspector: ^3.3.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Localization json files
    - locale/en.json
    - locale/ar.json
    # Images
    - assets/images/
    - assets/images/onboarding/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
